export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAILED'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const INIT = 'INIT'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_USER_DATA_LOADING = 'GET_USER_DATA_LOADING'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'

export const QUERY_PROFESSORS = 'QUERY_PROFESSORS'
export const QUERY_PROFESSORS_LOADING = 'QUERY_PROFESSORS_LOADING'
export const QUERY_PROFESSORS_FAIL = 'QUERY_PROFESSORS_FAIL'
export const QUERY_PROFESSORS_SUCCESS = 'QUERY_PROFESSORS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const UPDATE_FILTER = 'UPDATE_FILTER'
export const SORT_PROFESSORS = 'SORT_PROFESSORS'

